// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiTest.Models;

public partial class Posts
{
    public Guid Id { get; set; }

    public string Description { get; set; }
}