// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiTest.Models;

public partial class Products
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public short UnitsInStock { get; set; }

    public decimal UnitPrice { get; set; }
}